<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsTestProject>true</IsTestProject>
        <IsPackable>false</IsPackable>

        <UsePackageReference>false</UsePackageReference>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />

        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>

        <PackageReference Include="xunit.v3" Version="4.0.1" />
    </ItemGroup>

    <ItemGroup Condition="'$(UsePackageReference)' != 'true'">
        <ProjectReference Include="..\Majo.TerminalUI\Majo.TerminalUI.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(UsePackageReference)' == 'true'">
        <PackageReference Include="Majo.TerminalUI" Version="*-*" />
    </ItemGroup>

</Project>